---
title: "Visualize demonym contexts"
output: html_notebook
---

```{r Import libraries}
library(ComplexUpset) # note: this required a hotfix, remotes::install_github("federicomarini/complex-upset")
library(ggrepel)
library(tidyverse)
```

```{r Import data}
# Import the counts and add the dates
contexts_daily <- read_tsv("tables/contexts_summed_demonyms(2).tsv")
contexts_daily$date <- rev(seq(as.Date("2025-12-31"), by = "-1 day", length.out = nrow(contexts_daily))) # add dates
```

```{r Visualize}
contexts_daily_tall <- contexts_daily %>%
  pivot_longer(cols=c("biology","culture","intro","origins","raceeth","reference","other"),
               names_to = "context")

label_data <- contexts_daily_tall %>%
  group_by(context) %>%
  filter(date == max(date)) %>%
  slice(1) %>%
  ungroup()

custom_labels <- c(
  "biology"   = "Biology",
  "culture"   = "Culture",
  "intro"     = "Introduction",
  "origins"   = "Origins",
  "raceeth"   = "Race/ethnicity",
  "reference" = "Reference",
  "other"     = "Other"
)

context_colours = c(
  "biology"   = "#EECC66",
  "culture"   = "#EE99AA",
  "intro"     = "#6699CC",
  "origins"   = "#997700",
  "raceeth"   = "#994455",
  "reference" = "#004488",
  "other"     = "#000000"
)

# labels = names(keep_cols) %>% setNames(keep_cols)

ggplot(contexts_daily_tall, aes(x=date, y=value, colour=context)) + 
  geom_line() + 
  geom_text_repel(
    data = label_data,
    aes(
      x=date, label = custom_labels[context], colour = context, y=value
      ),
    family      = "sans",
    fontface    = "bold",
    size        = 3.2,
    direction   = "y",           # repel vertically only
    xlim        = c(as.Date("2025-12-31") + label_push, NA),  # push labels past the last date
    hjust       = 0,
    segment.size      = .5,
    segment.alpha     = .5,
    segment.linetype  = "dotted",
    segment.curvature = -0.1,
    segment.ncp       = 3,
    segment.angle     = 20,
    box.padding       = .4
  ) +
  theme_endline() +
  xlab("Date") + ylab("Number of pages") +
  ggtitle("Section contexts for genetics keywords (demonyms)") +
  coord_cartesian(clip = "off") +
  #scale_colour_manual(values = context_colours) +
  scale_colour_manual(
    values = c(
      rcartocolor::carto_pal(
        n    = n_distinct(custom_labels),
        name = "Bold"
        )
      )
    ) +
  scale_x_date(
    expand = c(0, 0),
    limits = c(as.Date("2001-01-01"), as.Date("2025-12-31") + 500),  # extra room for labels, originally 25
    date_breaks = "5 years",
    date_labels = "%Y"
  )

#ggsave("figures/section_contexts_demonyms.svg", device="svg", dpi=300,
#       width=10, height=6)

```

```{r Visualize upset plot}

upset_data <- read_tsv("tables/contexts_upset_demonyms_20260724.tsv") %>%
  select(-revision)#, -intro, -other)

colnames(upset_data) <- c("Introduction","Biology","Culture","Origins","Race/ethnicity", "Reference", "Other")
      
cats <- colnames(upset_data)

palette <- c(
  "Introduction"   = "#3969AC",
  "Biology"        = "#7F3C8D",
  "Culture"        = "#11A579",
  "Origins"        = "#F2B701",
  "Race/ethnicity" = "#80BA5A",
  "Reference"      = "#A5AA99",
  "Other"          = "#E73F74"
)

#queries <- lapply(names(palette), function(s) {
#  upset_query(set = s, fill = palette[[s]])
#})

queries <- lapply(names(palette), function(s) {
  upset_query(
    set = s,
    fill = palette[[s]],
    color = palette[[s]],
    only_components = c("overall_sizes", "intersections_matrix")
  )
})

upset(
  upset_data, cats,
  name = "Context",
  sort_intersections_by = "cardinality",
  width_ratio = 0.2,
  min_size = 2,
  queries = queries,
  base_annotations = list(
    'Intersection size' = intersection_size(counts = TRUE, text = list(size = 3))
      + theme(panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.background = element_rect(fill = "grey98", colour = NA),
              plot.background  = element_rect(fill = "grey98", colour = NA)
  )
)


```